language: csharp
os:
  - linux
  - osx

script:
  - chmod +x build.sh
  - ./build.sh --verbosity normal --target Travis

cache:
  directories:
    - packages
    - tools

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4a4095f0f21d178196c4
    on_success: change
    on_failure: always
    on_start: never
