version: 2.0.2.{build}
branches:
  except:
  - ci/travis
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- nuget restore Faker.sln
cache: packages -> **\packages.config
nuget:
  disable_publish_on_pr: true
build:
  project: Faker.sln
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
after_build:
- 7z a "Faker.NET.Portable-%APPVEYOR_BUILD_VERSION%.zip" "%APPVEYOR_BUILD_FOLDER%\src\Faker\bin\%CONFIGURATION%\*" -x!*CodeAnalysis* -r -mx=9
- nuget pack -Symbols -Version %APPVEYOR_BUILD_VERSION% Faker.NET.Portable.nuspec
test_script:
- nuget install OpenCover -Version 4.6.166 -OutputDirectory packages
- packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -target:nunit-console.exe "-targetargs:tests\Faker.Tests\bin\%CONFIGURATION%\Faker.Tests.dll /framework:net-4.0 /noshadow" -filter:"+[Faker*]Faker* -[*Tests*]*" -skipautoprops -output:opencovertests.xml -returntargetcode
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- codecov -f "opencovertests.xml"
artifacts:
- path: '*.zip'
- path: '*.nupkg'
deploy:
- provider: Environment
  name: NuGetRelease
  on:
    branch: master
- provider: Environment
  name: GithubRelease
  on:
    branch: master