version: 2.0.0.{build}
branches:
  except:
  - ci/travis
configuration: Release
assembly_info:
  patch: true
  file: src\Faker\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-alpha'
install:
- nuget restore Faker.sln
cache: packages
nuget:
  disable_publish_on_pr: true
build:
  project: Faker.sln
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
after_build:
- 7z a "Faker.NET.Portable-%APPVEYOR_BUILD_VERSION%.zip" "%APPVEYOR_BUILD_FOLDER%\src\Faker\bin\%CONFIGURATION%\*" -x!*CodeAnalysis* -r -mx=9
artifacts:
- path: '*.zip'
- path: '*.nupkg'
deploy:
- provider: Environment
  name: NuGetRelease
  on:
    branch: master
- provider: Environment
  name: GithubRelease
  on:
    branch: master